// Copyright (c) Mondoo, Inc.
// SPDX-License-Identifier: BUSL-1.1
//
// Code generated by gen.go; DO NOT EDIT.

package provider

import (
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	mondoov1 "go.mondoo.com/mondoo-go"
)

// credentialResourceModel is the state of a mondoo_credential. Exactly one of
// the kind attributes below is set; which one it is determines the kind, which
// is immutable after creation.
type credentialResourceModel struct {
	// scope
	SpaceID  types.String `tfsdk:"space_id"`
	ScopeMrn types.String `tfsdk:"scope_mrn"`

	// credential details
	Name types.String `tfsdk:"name"`

	// computed
	Mrn             types.String `tfsdk:"mrn"`
	OwnerMrn        types.String `tfsdk:"owner_mrn"`
	Kind            types.String `tfsdk:"kind"`
	HealthStatus    types.String `tfsdk:"health_status"`
	HealthCheckedAt types.String `tfsdk:"health_checked_at"`
	HealthError     types.String `tfsdk:"health_error"`
	ExpiresAt       types.String `tfsdk:"expires_at"`
	CreatedAt       types.String `tfsdk:"created_at"`
	UpdatedAt       types.String `tfsdk:"updated_at"`
	CreatedBy       types.String `tfsdk:"created_by"`
	FieldValues     types.Map    `tfsdk:"field_values"`
	Usages          types.List   `tfsdk:"usages"`

	// one per arm of mondoov1.CredentialV2SecretInput
	GithubPat *credentialGithubPatModel `tfsdk:"github_pat"`
	Slack     *credentialSlackModel     `tfsdk:"slack"`
	Aws       *credentialAwsModel       `tfsdk:"aws"`
}

type credentialGithubPatModel struct {
	Token   types.String `tfsdk:"token"`
	BaseUrl types.String `tfsdk:"base_url"`
}

type credentialSlackModel struct {
	BotToken types.String `tfsdk:"bot_token"`
}

type credentialAwsModel struct {
	AccessKeyId     types.String `tfsdk:"access_key_id"`
	SecretAccessKey types.String `tfsdk:"secret_access_key"`
	Region          types.String `tfsdk:"region"`
}

// credentialSecretAttributes returns one Optional SingleNestedAttribute per
// credential kind. Every field is Sensitive without exception: the value comes
// from configuration and would otherwise be rendered in plan output, and a rule
// with no carve-outs is the only one that stays correct as kinds are added.
func credentialSecretAttributes() map[string]schema.Attribute {
	return map[string]schema.Attribute{
		"github_pat": schema.SingleNestedAttribute{
			MarkdownDescription: "Secret for a `" + string(mondoov1.CredentialV2KindGithubPat) + "` credential.",
			Optional:            true,
			Attributes: map[string]schema.Attribute{
				"token": schema.StringAttribute{
					Required:  true,
					Sensitive: true,
				},
				"base_url": schema.StringAttribute{
					Optional:  true,
					Sensitive: true,
				},
			},
		},
		"slack": schema.SingleNestedAttribute{
			MarkdownDescription: "Secret for a `" + string(mondoov1.CredentialV2KindSlack) + "` credential.",
			Optional:            true,
			Attributes: map[string]schema.Attribute{
				"bot_token": schema.StringAttribute{
					Required:  true,
					Sensitive: true,
				},
			},
		},
		"aws": schema.SingleNestedAttribute{
			MarkdownDescription: "Secret for a `" + string(mondoov1.CredentialV2KindAws) + "` credential.",
			Optional:            true,
			Attributes: map[string]schema.Attribute{
				"access_key_id": schema.StringAttribute{
					Required:  true,
					Sensitive: true,
				},
				"secret_access_key": schema.StringAttribute{
					Required:  true,
					Sensitive: true,
				},
				"region": schema.StringAttribute{
					Optional:  true,
					Sensitive: true,
				},
			},
		},
	}
}

// credentialSecretPaths returns the ExactlyOneOf path set. It is generated from
// the SDK type, so it is total by construction rather than by maintenance.
func credentialSecretPaths() []path.Expression {
	return []path.Expression{
		path.MatchRoot("github_pat"),
		path.MatchRoot("slack"),
		path.MatchRoot("aws"),
	}
}

// BuildSecretInput builds the secret input from whichever kind attribute is
// set. Every field of that arm is sent, every time: rotateCredentialV2 replaces
// the whole payload rather than merging it, so an omitted baseUrl resets a
// GitHub Enterprise credential to github.com and an omitted region resets AWS
// to us-east-1.
func (m *credentialResourceModel) BuildSecretInput() (mondoov1.CredentialV2SecretInput, error) {
	var (
		in  mondoov1.CredentialV2SecretInput
		set int
	)

	if m.GithubPat != nil {
		set++
		in.GithubPat = &mondoov1.GithubPatCredentialV2Input{
			Token:   mondoov1.String(m.GithubPat.Token.ValueString()),
			BaseUrl: credentialOptionalString(m.GithubPat.BaseUrl),
		}
	}

	if m.Slack != nil {
		set++
		in.Slack = &mondoov1.SlackCredentialV2Input{
			BotToken: mondoov1.String(m.Slack.BotToken.ValueString()),
		}
	}

	if m.Aws != nil {
		set++
		in.Aws = &mondoov1.AwsCredentialV2Input{
			AccessKeyId:     mondoov1.String(m.Aws.AccessKeyId.ValueString()),
			SecretAccessKey: mondoov1.String(m.Aws.SecretAccessKey.ValueString()),
			Region:          credentialOptionalString(m.Aws.Region),
		}
	}

	if set != 1 {
		return in, fmt.Errorf("exactly one credential kind attribute must be set, found %d", set)
	}
	return in, nil
}

// SecretKind reports the kind implied by whichever attribute is set.
func (m *credentialResourceModel) SecretKind() (mondoov1.CredentialV2Kind, error) {
	var (
		kind mondoov1.CredentialV2Kind
		set  int
	)

	if m.GithubPat != nil {
		set++
		kind = mondoov1.CredentialV2KindGithubPat
	}

	if m.Slack != nil {
		set++
		kind = mondoov1.CredentialV2KindSlack
	}

	if m.Aws != nil {
		set++
		kind = mondoov1.CredentialV2KindAws
	}

	if set != 1 {
		return kind, fmt.Errorf("exactly one credential kind attribute must be set, found %d", set)
	}
	return kind, nil
}
