// Copyright (c) Mondoo, Inc.
// SPDX-License-Identifier: BUSL-1.1
//
// Code generated by gen.go; DO NOT EDIT.

package provider

import (
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	mondoov1 "go.mondoo.com/mondoo-go"
)

// credentialResourceModel is the state of a mondoo_credential. Exactly one of
// the kind attributes below is set; which one it is determines the kind, which
// is immutable after creation.
type credentialResourceModel struct {
	// scope
	SpaceID  types.String `tfsdk:"space_id"`
	ScopeMrn types.String `tfsdk:"scope_mrn"`

	// credential details
	Name types.String `tfsdk:"name"`

	// computed
	Mrn             types.String `tfsdk:"mrn"`
	OwnerMrn        types.String `tfsdk:"owner_mrn"`
	Kind            types.String `tfsdk:"kind"`
	HealthStatus    types.String `tfsdk:"health_status"`
	HealthCheckedAt types.String `tfsdk:"health_checked_at"`
	HealthError     types.String `tfsdk:"health_error"`
	ExpiresAt       types.String `tfsdk:"expires_at"`
	CreatedAt       types.String `tfsdk:"created_at"`
	UpdatedAt       types.String `tfsdk:"updated_at"`
	CreatedBy       types.String `tfsdk:"created_by"`
	FieldValues     types.Map    `tfsdk:"field_values"`
	Usages          types.List   `tfsdk:"usages"`

	// one per arm of mondoov1.CredentialV2SecretInput
	GithubPat                *credentialGithubPatModel                `tfsdk:"github_pat"`
	GithubApp                *credentialGithubAppModel                `tfsdk:"github_app"`
	Slack                    *credentialSlackModel                    `tfsdk:"slack"`
	Aws                      *credentialAwsModel                      `tfsdk:"aws"`
	Crowdstrike              *credentialCrowdstrikeModel              `tfsdk:"crowdstrike"`
	Anthropic                *credentialAnthropicModel                `tfsdk:"anthropic"`
	SpritesToken             *credentialSpritesTokenModel             `tfsdk:"sprites_token"`
	SpritesFlyMacaroon       *credentialSpritesFlyMacaroonModel       `tfsdk:"sprites_fly_macaroon"`
	ShodanApiKey             *credentialShodanApiKeyModel             `tfsdk:"shodan_api_key"`
	CloudflareApiToken       *credentialCloudflareApiTokenModel       `tfsdk:"cloudflare_api_token"`
	HetznerApiToken          *credentialHetznerApiTokenModel          `tfsdk:"hetzner_api_token"`
	DigitaloceanApiToken     *credentialDigitaloceanApiTokenModel     `tfsdk:"digitalocean_api_token"`
	VercelApiToken           *credentialVercelApiTokenModel           `tfsdk:"vercel_api_token"`
	OktaApiToken             *credentialOktaApiTokenModel             `tfsdk:"okta_api_token"`
	GitlabToken              *credentialGitlabTokenModel              `tfsdk:"gitlab_token"`
	EntraClientSecret        *credentialEntraClientSecretModel        `tfsdk:"entra_client_secret"`
	EntraCertificate         *credentialEntraCertificateModel         `tfsdk:"entra_certificate"`
	GcpServiceAccount        *credentialGcpServiceAccountModel        `tfsdk:"gcp_service_account"`
	NextdnsApiKey            *credentialNextdnsApiKeyModel            `tfsdk:"nextdns_api_key"`
	TailscaleApiKey          *credentialTailscaleApiKeyModel          `tfsdk:"tailscale_api_key"`
	TailscaleOauthClient     *credentialTailscaleOauthClientModel     `tfsdk:"tailscale_oauth_client"`
	StackitServiceAccountKey *credentialStackitServiceAccountKeyModel `tfsdk:"stackit_service_account_key"`
	MongodbAtlas             *credentialMongodbAtlasModel             `tfsdk:"mongodb_atlas"`
	DatabricksOauth          *credentialDatabricksOauthModel          `tfsdk:"databricks_oauth"`
	OciApiKey                *credentialOciApiKeyModel                `tfsdk:"oci_api_key"`
	SnowflakeKeypair         *credentialSnowflakeKeypairModel         `tfsdk:"snowflake_keypair"`
	Jira                     *credentialJiraModel                     `tfsdk:"jira"`
	Zendesk                  *credentialZendeskModel                  `tfsdk:"zendesk"`
	JamfOauth                *credentialJamfOauthModel                `tfsdk:"jamf_oauth"`
	TenableIo                *credentialTenableIoModel                `tfsdk:"tenable_io"`
	SnykApiToken             *credentialSnykApiTokenModel             `tfsdk:"snyk_api_token"`
	SonarqubeToken           *credentialSonarqubeTokenModel           `tfsdk:"sonarqube_token"`
	ElasticApiKey            *credentialElasticApiKeyModel            `tfsdk:"elastic_api_key"`
	S3AccessKey              *credentialS3AccessKeyModel              `tfsdk:"s3_access_key"`
	TenableSc                *credentialTenableScModel                `tfsdk:"tenable_sc"`
	Qualys                   *credentialQualysModel                   `tfsdk:"qualys"`
	SecurityScorecard        *credentialSecurityScorecardModel        `tfsdk:"security_scorecard"`
	JfrogAccessToken         *credentialJfrogAccessTokenModel         `tfsdk:"jfrog_access_token"`
	AzureBlobSas             *credentialAzureBlobSasModel             `tfsdk:"azure_blob_sas"`
	SnowflakePassword        *credentialSnowflakePasswordModel        `tfsdk:"snowflake_password"`
	SplunkHecToken           *credentialSplunkHecTokenModel           `tfsdk:"splunk_hec_token"`
	KandjiApiToken           *credentialKandjiApiTokenModel           `tfsdk:"kandji_api_token"`
	OpenvasCloud             *credentialOpenvasCloudModel             `tfsdk:"openvas_cloud"`
	Sentinelone              *credentialSentineloneModel              `tfsdk:"sentinelone"`
}

type credentialGithubPatModel struct {
	Token   types.String `tfsdk:"token"`
	BaseUrl types.String `tfsdk:"base_url"`
}

type credentialGithubAppModel struct {
	AppId      types.String `tfsdk:"app_id"`
	PrivateKey types.String `tfsdk:"private_key"`
}

type credentialSlackModel struct {
	BotToken types.String `tfsdk:"bot_token"`
}

type credentialAwsModel struct {
	AccessKeyId     types.String `tfsdk:"access_key_id"`
	SecretAccessKey types.String `tfsdk:"secret_access_key"`
	Region          types.String `tfsdk:"region"`
}

type credentialCrowdstrikeModel struct {
	ClientId     types.String `tfsdk:"client_id"`
	ClientSecret types.String `tfsdk:"client_secret"`
	BaseUrl      types.String `tfsdk:"base_url"`
}

type credentialAnthropicModel struct {
	ApiKey types.String `tfsdk:"api_key"`
}

type credentialSpritesTokenModel struct {
	Token   types.String `tfsdk:"token"`
	BaseUrl types.String `tfsdk:"base_url"`
}

type credentialSpritesFlyMacaroonModel struct {
	Macaroon types.String `tfsdk:"macaroon"`
	Org      types.String `tfsdk:"org"`
	BaseUrl  types.String `tfsdk:"base_url"`
}

type credentialShodanApiKeyModel struct {
	ApiKey types.String `tfsdk:"api_key"`
}

type credentialCloudflareApiTokenModel struct {
	ApiToken types.String `tfsdk:"api_token"`
}

type credentialHetznerApiTokenModel struct {
	ApiToken types.String `tfsdk:"api_token"`
}

type credentialDigitaloceanApiTokenModel struct {
	ApiToken types.String `tfsdk:"api_token"`
}

type credentialVercelApiTokenModel struct {
	ApiToken types.String `tfsdk:"api_token"`
}

type credentialOktaApiTokenModel struct {
	Domain   types.String `tfsdk:"domain"`
	ApiToken types.String `tfsdk:"api_token"`
}

type credentialGitlabTokenModel struct {
	Token   types.String `tfsdk:"token"`
	BaseUrl types.String `tfsdk:"base_url"`
}

type credentialEntraClientSecretModel struct {
	TenantId     types.String `tfsdk:"tenant_id"`
	ClientId     types.String `tfsdk:"client_id"`
	ClientSecret types.String `tfsdk:"client_secret"`
}

type credentialEntraCertificateModel struct {
	TenantId    types.String `tfsdk:"tenant_id"`
	ClientId    types.String `tfsdk:"client_id"`
	Certificate types.String `tfsdk:"certificate"`
}

type credentialGcpServiceAccountModel struct {
	CredentialsJson types.String `tfsdk:"credentials_json"`
}

type credentialNextdnsApiKeyModel struct {
	ApiKey types.String `tfsdk:"api_key"`
}

type credentialTailscaleApiKeyModel struct {
	ApiKey types.String `tfsdk:"api_key"`
}

type credentialTailscaleOauthClientModel struct {
	ClientId     types.String `tfsdk:"client_id"`
	ClientSecret types.String `tfsdk:"client_secret"`
}

type credentialStackitServiceAccountKeyModel struct {
	ServiceAccountKey types.String `tfsdk:"service_account_key"`
}

type credentialMongodbAtlasModel struct {
	PublicKey  types.String `tfsdk:"public_key"`
	PrivateKey types.String `tfsdk:"private_key"`
}

type credentialDatabricksOauthModel struct {
	Host         types.String `tfsdk:"host"`
	ClientId     types.String `tfsdk:"client_id"`
	ClientSecret types.String `tfsdk:"client_secret"`
}

type credentialOciApiKeyModel struct {
	TenancyOcid types.String `tfsdk:"tenancy_ocid"`
	UserOcid    types.String `tfsdk:"user_ocid"`
	Region      types.String `tfsdk:"region"`
	Fingerprint types.String `tfsdk:"fingerprint"`
	PrivateKey  types.String `tfsdk:"private_key"`
}

type credentialSnowflakeKeypairModel struct {
	Account    types.String `tfsdk:"account"`
	User       types.String `tfsdk:"user"`
	PrivateKey types.String `tfsdk:"private_key"`
}

type credentialJiraModel struct {
	Host     types.String `tfsdk:"host"`
	Email    types.String `tfsdk:"email"`
	ApiToken types.String `tfsdk:"api_token"`
	CloudId  types.String `tfsdk:"cloud_id"`
}

type credentialZendeskModel struct {
	Subdomain types.String `tfsdk:"subdomain"`
	Email     types.String `tfsdk:"email"`
	ApiToken  types.String `tfsdk:"api_token"`
}

type credentialJamfOauthModel struct {
	BaseUrl      types.String `tfsdk:"base_url"`
	ClientId     types.String `tfsdk:"client_id"`
	ClientSecret types.String `tfsdk:"client_secret"`
}

type credentialTenableIoModel struct {
	AccessKey types.String `tfsdk:"access_key"`
	SecretKey types.String `tfsdk:"secret_key"`
	BaseUrl   types.String `tfsdk:"base_url"`
}

type credentialSnykApiTokenModel struct {
	ApiToken types.String `tfsdk:"api_token"`
	BaseUrl  types.String `tfsdk:"base_url"`
}

type credentialSonarqubeTokenModel struct {
	Token   types.String `tfsdk:"token"`
	BaseUrl types.String `tfsdk:"base_url"`
}

type credentialElasticApiKeyModel struct {
	ApiKey   types.String `tfsdk:"api_key"`
	Endpoint types.String `tfsdk:"endpoint"`
	CloudId  types.String `tfsdk:"cloud_id"`
}

type credentialS3AccessKeyModel struct {
	Endpoint        types.String `tfsdk:"endpoint"`
	AccessKeyId     types.String `tfsdk:"access_key_id"`
	SecretAccessKey types.String `tfsdk:"secret_access_key"`
	Region          types.String `tfsdk:"region"`
}

type credentialTenableScModel struct {
	ServerUrl types.String `tfsdk:"server_url"`
	AccessKey types.String `tfsdk:"access_key"`
	SecretKey types.String `tfsdk:"secret_key"`
}

type credentialQualysModel struct {
	BaseUrl  types.String `tfsdk:"base_url"`
	Username types.String `tfsdk:"username"`
	Password types.String `tfsdk:"password"`
}

type credentialSecurityScorecardModel struct {
	ApiToken types.String `tfsdk:"api_token"`
}

type credentialJfrogAccessTokenModel struct {
	BaseUrl     types.String `tfsdk:"base_url"`
	AccessToken types.String `tfsdk:"access_token"`
}

type credentialAzureBlobSasModel struct {
	SasUrl types.String `tfsdk:"sas_url"`
}

type credentialSnowflakePasswordModel struct {
	Account  types.String `tfsdk:"account"`
	User     types.String `tfsdk:"user"`
	Password types.String `tfsdk:"password"`
}

type credentialSplunkHecTokenModel struct {
	Host  types.String `tfsdk:"host"`
	Token types.String `tfsdk:"token"`
}

type credentialKandjiApiTokenModel struct {
	ApiUrl   types.String `tfsdk:"api_url"`
	ApiToken types.String `tfsdk:"api_token"`
}

type credentialOpenvasCloudModel struct {
	ApiToken types.String `tfsdk:"api_token"`
	BaseUrl  types.String `tfsdk:"base_url"`
}

type credentialSentineloneModel struct {
	Host     types.String `tfsdk:"host"`
	ApiToken types.String `tfsdk:"api_token"`
}

// credentialSecretAttributes returns one Optional SingleNestedAttribute per
// credential kind. Every field is Sensitive without exception: the value comes
// from configuration and would otherwise be rendered in plan output, and a rule
// with no carve-outs is the only one that stays correct as kinds are added.
func credentialSecretAttributes() map[string]schema.Attribute {
	return map[string]schema.Attribute{
		"github_pat": schema.SingleNestedAttribute{
			MarkdownDescription: "Secret for a `" + string(mondoov1.CredentialV2KindGithubPat) + "` credential.",
			Optional:            true,
			Attributes: map[string]schema.Attribute{
				"token": schema.StringAttribute{
					Required:  true,
					Sensitive: true,
				},
				"base_url": schema.StringAttribute{
					Optional:  true,
					Sensitive: true,
				},
			},
		},
		"github_app": schema.SingleNestedAttribute{
			MarkdownDescription: "Secret for a `" + string(mondoov1.CredentialV2KindGithubApp) + "` credential.",
			Optional:            true,
			Attributes: map[string]schema.Attribute{
				"app_id": schema.StringAttribute{
					Required:  true,
					Sensitive: true,
				},
				"private_key": schema.StringAttribute{
					Required:  true,
					Sensitive: true,
				},
			},
		},
		"slack": schema.SingleNestedAttribute{
			MarkdownDescription: "Secret for a `" + string(mondoov1.CredentialV2KindSlack) + "` credential.",
			Optional:            true,
			Attributes: map[string]schema.Attribute{
				"bot_token": schema.StringAttribute{
					Required:  true,
					Sensitive: true,
				},
			},
		},
		"aws": schema.SingleNestedAttribute{
			MarkdownDescription: "Secret for a `" + string(mondoov1.CredentialV2KindAws) + "` credential.",
			Optional:            true,
			Attributes: map[string]schema.Attribute{
				"access_key_id": schema.StringAttribute{
					Required:  true,
					Sensitive: true,
				},
				"secret_access_key": schema.StringAttribute{
					Required:  true,
					Sensitive: true,
				},
				"region": schema.StringAttribute{
					Optional:  true,
					Sensitive: true,
				},
			},
		},
		"crowdstrike": schema.SingleNestedAttribute{
			MarkdownDescription: "Secret for a `" + string(mondoov1.CredentialV2KindCrowdstrike) + "` credential.",
			Optional:            true,
			Attributes: map[string]schema.Attribute{
				"client_id": schema.StringAttribute{
					Required:  true,
					Sensitive: true,
				},
				"client_secret": schema.StringAttribute{
					Required:  true,
					Sensitive: true,
				},
				"base_url": schema.StringAttribute{
					Optional:  true,
					Sensitive: true,
				},
			},
		},
		"anthropic": schema.SingleNestedAttribute{
			MarkdownDescription: "Secret for a `" + string(mondoov1.CredentialV2KindAnthropic) + "` credential.",
			Optional:            true,
			Attributes: map[string]schema.Attribute{
				"api_key": schema.StringAttribute{
					Required:  true,
					Sensitive: true,
				},
			},
		},
		"sprites_token": schema.SingleNestedAttribute{
			MarkdownDescription: "Secret for a `" + string(mondoov1.CredentialV2KindSpritesToken) + "` credential.",
			Optional:            true,
			Attributes: map[string]schema.Attribute{
				"token": schema.StringAttribute{
					Required:  true,
					Sensitive: true,
				},
				"base_url": schema.StringAttribute{
					Optional:  true,
					Sensitive: true,
				},
			},
		},
		"sprites_fly_macaroon": schema.SingleNestedAttribute{
			MarkdownDescription: "Secret for a `" + string(mondoov1.CredentialV2KindSpritesFlyMacaroon) + "` credential.",
			Optional:            true,
			Attributes: map[string]schema.Attribute{
				"macaroon": schema.StringAttribute{
					Required:  true,
					Sensitive: true,
				},
				"org": schema.StringAttribute{
					Optional:  true,
					Sensitive: true,
				},
				"base_url": schema.StringAttribute{
					Optional:  true,
					Sensitive: true,
				},
			},
		},
		"shodan_api_key": schema.SingleNestedAttribute{
			MarkdownDescription: "Secret for a `" + string(mondoov1.CredentialV2KindShodanApiKey) + "` credential.",
			Optional:            true,
			Attributes: map[string]schema.Attribute{
				"api_key": schema.StringAttribute{
					Required:  true,
					Sensitive: true,
				},
			},
		},
		"cloudflare_api_token": schema.SingleNestedAttribute{
			MarkdownDescription: "Secret for a `" + string(mondoov1.CredentialV2KindCloudflareApiToken) + "` credential.",
			Optional:            true,
			Attributes: map[string]schema.Attribute{
				"api_token": schema.StringAttribute{
					Required:  true,
					Sensitive: true,
				},
			},
		},
		"hetzner_api_token": schema.SingleNestedAttribute{
			MarkdownDescription: "Secret for a `" + string(mondoov1.CredentialV2KindHetznerApiToken) + "` credential.",
			Optional:            true,
			Attributes: map[string]schema.Attribute{
				"api_token": schema.StringAttribute{
					Required:  true,
					Sensitive: true,
				},
			},
		},
		"digitalocean_api_token": schema.SingleNestedAttribute{
			MarkdownDescription: "Secret for a `" + string(mondoov1.CredentialV2KindDigitaloceanApiToken) + "` credential.",
			Optional:            true,
			Attributes: map[string]schema.Attribute{
				"api_token": schema.StringAttribute{
					Required:  true,
					Sensitive: true,
				},
			},
		},
		"vercel_api_token": schema.SingleNestedAttribute{
			MarkdownDescription: "Secret for a `" + string(mondoov1.CredentialV2KindVercelApiToken) + "` credential.",
			Optional:            true,
			Attributes: map[string]schema.Attribute{
				"api_token": schema.StringAttribute{
					Required:  true,
					Sensitive: true,
				},
			},
		},
		"okta_api_token": schema.SingleNestedAttribute{
			MarkdownDescription: "Secret for a `" + string(mondoov1.CredentialV2KindOktaApiToken) + "` credential.",
			Optional:            true,
			Attributes: map[string]schema.Attribute{
				"domain": schema.StringAttribute{
					Required:  true,
					Sensitive: true,
				},
				"api_token": schema.StringAttribute{
					Required:  true,
					Sensitive: true,
				},
			},
		},
		"gitlab_token": schema.SingleNestedAttribute{
			MarkdownDescription: "Secret for a `" + string(mondoov1.CredentialV2KindGitlabToken) + "` credential.",
			Optional:            true,
			Attributes: map[string]schema.Attribute{
				"token": schema.StringAttribute{
					Required:  true,
					Sensitive: true,
				},
				"base_url": schema.StringAttribute{
					Optional:  true,
					Sensitive: true,
				},
			},
		},
		"entra_client_secret": schema.SingleNestedAttribute{
			MarkdownDescription: "Secret for a `" + string(mondoov1.CredentialV2KindEntraClientSecret) + "` credential.",
			Optional:            true,
			Attributes: map[string]schema.Attribute{
				"tenant_id": schema.StringAttribute{
					Required:  true,
					Sensitive: true,
				},
				"client_id": schema.StringAttribute{
					Required:  true,
					Sensitive: true,
				},
				"client_secret": schema.StringAttribute{
					Required:  true,
					Sensitive: true,
				},
			},
		},
		"entra_certificate": schema.SingleNestedAttribute{
			MarkdownDescription: "Secret for a `" + string(mondoov1.CredentialV2KindEntraCertificate) + "` credential.",
			Optional:            true,
			Attributes: map[string]schema.Attribute{
				"tenant_id": schema.StringAttribute{
					Required:  true,
					Sensitive: true,
				},
				"client_id": schema.StringAttribute{
					Required:  true,
					Sensitive: true,
				},
				"certificate": schema.StringAttribute{
					Required:  true,
					Sensitive: true,
				},
			},
		},
		"gcp_service_account": schema.SingleNestedAttribute{
			MarkdownDescription: "Secret for a `" + string(mondoov1.CredentialV2KindGcpServiceAccount) + "` credential.",
			Optional:            true,
			Attributes: map[string]schema.Attribute{
				"credentials_json": schema.StringAttribute{
					Required:  true,
					Sensitive: true,
				},
			},
		},
		"nextdns_api_key": schema.SingleNestedAttribute{
			MarkdownDescription: "Secret for a `" + string(mondoov1.CredentialV2KindNextdnsApiKey) + "` credential.",
			Optional:            true,
			Attributes: map[string]schema.Attribute{
				"api_key": schema.StringAttribute{
					Required:  true,
					Sensitive: true,
				},
			},
		},
		"tailscale_api_key": schema.SingleNestedAttribute{
			MarkdownDescription: "Secret for a `" + string(mondoov1.CredentialV2KindTailscaleApiKey) + "` credential.",
			Optional:            true,
			Attributes: map[string]schema.Attribute{
				"api_key": schema.StringAttribute{
					Required:  true,
					Sensitive: true,
				},
			},
		},
		"tailscale_oauth_client": schema.SingleNestedAttribute{
			MarkdownDescription: "Secret for a `" + string(mondoov1.CredentialV2KindTailscaleOauthClient) + "` credential.",
			Optional:            true,
			Attributes: map[string]schema.Attribute{
				"client_id": schema.StringAttribute{
					Required:  true,
					Sensitive: true,
				},
				"client_secret": schema.StringAttribute{
					Required:  true,
					Sensitive: true,
				},
			},
		},
		"stackit_service_account_key": schema.SingleNestedAttribute{
			MarkdownDescription: "Secret for a `" + string(mondoov1.CredentialV2KindStackitServiceAccountKey) + "` credential.",
			Optional:            true,
			Attributes: map[string]schema.Attribute{
				"service_account_key": schema.StringAttribute{
					Required:  true,
					Sensitive: true,
				},
			},
		},
		"mongodb_atlas": schema.SingleNestedAttribute{
			MarkdownDescription: "Secret for a `" + string(mondoov1.CredentialV2KindMongodbAtlas) + "` credential.",
			Optional:            true,
			Attributes: map[string]schema.Attribute{
				"public_key": schema.StringAttribute{
					Required:  true,
					Sensitive: true,
				},
				"private_key": schema.StringAttribute{
					Required:  true,
					Sensitive: true,
				},
			},
		},
		"databricks_oauth": schema.SingleNestedAttribute{
			MarkdownDescription: "Secret for a `" + string(mondoov1.CredentialV2KindDatabricksOauth) + "` credential.",
			Optional:            true,
			Attributes: map[string]schema.Attribute{
				"host": schema.StringAttribute{
					Required:  true,
					Sensitive: true,
				},
				"client_id": schema.StringAttribute{
					Required:  true,
					Sensitive: true,
				},
				"client_secret": schema.StringAttribute{
					Required:  true,
					Sensitive: true,
				},
			},
		},
		"oci_api_key": schema.SingleNestedAttribute{
			MarkdownDescription: "Secret for a `" + string(mondoov1.CredentialV2KindOciApiKey) + "` credential.",
			Optional:            true,
			Attributes: map[string]schema.Attribute{
				"tenancy_ocid": schema.StringAttribute{
					Required:  true,
					Sensitive: true,
				},
				"user_ocid": schema.StringAttribute{
					Required:  true,
					Sensitive: true,
				},
				"region": schema.StringAttribute{
					Required:  true,
					Sensitive: true,
				},
				"fingerprint": schema.StringAttribute{
					Required:  true,
					Sensitive: true,
				},
				"private_key": schema.StringAttribute{
					Required:  true,
					Sensitive: true,
				},
			},
		},
		"snowflake_keypair": schema.SingleNestedAttribute{
			MarkdownDescription: "Secret for a `" + string(mondoov1.CredentialV2KindSnowflakeKeypair) + "` credential.",
			Optional:            true,
			Attributes: map[string]schema.Attribute{
				"account": schema.StringAttribute{
					Required:  true,
					Sensitive: true,
				},
				"user": schema.StringAttribute{
					Required:  true,
					Sensitive: true,
				},
				"private_key": schema.StringAttribute{
					Required:  true,
					Sensitive: true,
				},
			},
		},
		"jira": schema.SingleNestedAttribute{
			MarkdownDescription: "Secret for a `" + string(mondoov1.CredentialV2KindJira) + "` credential.",
			Optional:            true,
			Attributes: map[string]schema.Attribute{
				"host": schema.StringAttribute{
					Required:  true,
					Sensitive: true,
				},
				"email": schema.StringAttribute{
					Required:  true,
					Sensitive: true,
				},
				"api_token": schema.StringAttribute{
					Required:  true,
					Sensitive: true,
				},
				"cloud_id": schema.StringAttribute{
					Optional:  true,
					Sensitive: true,
				},
			},
		},
		"zendesk": schema.SingleNestedAttribute{
			MarkdownDescription: "Secret for a `" + string(mondoov1.CredentialV2KindZendesk) + "` credential.",
			Optional:            true,
			Attributes: map[string]schema.Attribute{
				"subdomain": schema.StringAttribute{
					Required:  true,
					Sensitive: true,
				},
				"email": schema.StringAttribute{
					Required:  true,
					Sensitive: true,
				},
				"api_token": schema.StringAttribute{
					Required:  true,
					Sensitive: true,
				},
			},
		},
		"jamf_oauth": schema.SingleNestedAttribute{
			MarkdownDescription: "Secret for a `" + string(mondoov1.CredentialV2KindJamfOauth) + "` credential.",
			Optional:            true,
			Attributes: map[string]schema.Attribute{
				"base_url": schema.StringAttribute{
					Required:  true,
					Sensitive: true,
				},
				"client_id": schema.StringAttribute{
					Required:  true,
					Sensitive: true,
				},
				"client_secret": schema.StringAttribute{
					Required:  true,
					Sensitive: true,
				},
			},
		},
		"tenable_io": schema.SingleNestedAttribute{
			MarkdownDescription: "Secret for a `" + string(mondoov1.CredentialV2KindTenableIo) + "` credential.",
			Optional:            true,
			Attributes: map[string]schema.Attribute{
				"access_key": schema.StringAttribute{
					Required:  true,
					Sensitive: true,
				},
				"secret_key": schema.StringAttribute{
					Required:  true,
					Sensitive: true,
				},
				"base_url": schema.StringAttribute{
					Optional:  true,
					Sensitive: true,
				},
			},
		},
		"snyk_api_token": schema.SingleNestedAttribute{
			MarkdownDescription: "Secret for a `" + string(mondoov1.CredentialV2KindSnykApiToken) + "` credential.",
			Optional:            true,
			Attributes: map[string]schema.Attribute{
				"api_token": schema.StringAttribute{
					Required:  true,
					Sensitive: true,
				},
				"base_url": schema.StringAttribute{
					Optional:  true,
					Sensitive: true,
				},
			},
		},
		"sonarqube_token": schema.SingleNestedAttribute{
			MarkdownDescription: "Secret for a `" + string(mondoov1.CredentialV2KindSonarqubeToken) + "` credential.",
			Optional:            true,
			Attributes: map[string]schema.Attribute{
				"token": schema.StringAttribute{
					Required:  true,
					Sensitive: true,
				},
				"base_url": schema.StringAttribute{
					Optional:  true,
					Sensitive: true,
				},
			},
		},
		"elastic_api_key": schema.SingleNestedAttribute{
			MarkdownDescription: "Secret for a `" + string(mondoov1.CredentialV2KindElasticApiKey) + "` credential.",
			Optional:            true,
			Attributes: map[string]schema.Attribute{
				"api_key": schema.StringAttribute{
					Required:  true,
					Sensitive: true,
				},
				"endpoint": schema.StringAttribute{
					Optional:  true,
					Sensitive: true,
				},
				"cloud_id": schema.StringAttribute{
					Optional:  true,
					Sensitive: true,
				},
			},
		},
		"s3_access_key": schema.SingleNestedAttribute{
			MarkdownDescription: "Secret for a `" + string(mondoov1.CredentialV2KindS3AccessKey) + "` credential.",
			Optional:            true,
			Attributes: map[string]schema.Attribute{
				"endpoint": schema.StringAttribute{
					Required:  true,
					Sensitive: true,
				},
				"access_key_id": schema.StringAttribute{
					Required:  true,
					Sensitive: true,
				},
				"secret_access_key": schema.StringAttribute{
					Required:  true,
					Sensitive: true,
				},
				"region": schema.StringAttribute{
					Optional:  true,
					Sensitive: true,
				},
			},
		},
		"tenable_sc": schema.SingleNestedAttribute{
			MarkdownDescription: "Secret for a `" + string(mondoov1.CredentialV2KindTenableSc) + "` credential.",
			Optional:            true,
			Attributes: map[string]schema.Attribute{
				"server_url": schema.StringAttribute{
					Required:  true,
					Sensitive: true,
				},
				"access_key": schema.StringAttribute{
					Required:  true,
					Sensitive: true,
				},
				"secret_key": schema.StringAttribute{
					Required:  true,
					Sensitive: true,
				},
			},
		},
		"qualys": schema.SingleNestedAttribute{
			MarkdownDescription: "Secret for a `" + string(mondoov1.CredentialV2KindQualys) + "` credential.",
			Optional:            true,
			Attributes: map[string]schema.Attribute{
				"base_url": schema.StringAttribute{
					Required:  true,
					Sensitive: true,
				},
				"username": schema.StringAttribute{
					Required:  true,
					Sensitive: true,
				},
				"password": schema.StringAttribute{
					Required:  true,
					Sensitive: true,
				},
			},
		},
		"security_scorecard": schema.SingleNestedAttribute{
			MarkdownDescription: "Secret for a `" + string(mondoov1.CredentialV2KindSecurityScorecard) + "` credential.",
			Optional:            true,
			Attributes: map[string]schema.Attribute{
				"api_token": schema.StringAttribute{
					Required:  true,
					Sensitive: true,
				},
			},
		},
		"jfrog_access_token": schema.SingleNestedAttribute{
			MarkdownDescription: "Secret for a `" + string(mondoov1.CredentialV2KindJfrogAccessToken) + "` credential.",
			Optional:            true,
			Attributes: map[string]schema.Attribute{
				"base_url": schema.StringAttribute{
					Required:  true,
					Sensitive: true,
				},
				"access_token": schema.StringAttribute{
					Required:  true,
					Sensitive: true,
				},
			},
		},
		"azure_blob_sas": schema.SingleNestedAttribute{
			MarkdownDescription: "Secret for a `" + string(mondoov1.CredentialV2KindAzureBlobSas) + "` credential.",
			Optional:            true,
			Attributes: map[string]schema.Attribute{
				"sas_url": schema.StringAttribute{
					Required:  true,
					Sensitive: true,
				},
			},
		},
		"snowflake_password": schema.SingleNestedAttribute{
			MarkdownDescription: "Secret for a `" + string(mondoov1.CredentialV2KindSnowflakePassword) + "` credential.",
			Optional:            true,
			Attributes: map[string]schema.Attribute{
				"account": schema.StringAttribute{
					Required:  true,
					Sensitive: true,
				},
				"user": schema.StringAttribute{
					Required:  true,
					Sensitive: true,
				},
				"password": schema.StringAttribute{
					Required:  true,
					Sensitive: true,
				},
			},
		},
		"splunk_hec_token": schema.SingleNestedAttribute{
			MarkdownDescription: "Secret for a `" + string(mondoov1.CredentialV2KindSplunkHecToken) + "` credential.",
			Optional:            true,
			Attributes: map[string]schema.Attribute{
				"host": schema.StringAttribute{
					Required:  true,
					Sensitive: true,
				},
				"token": schema.StringAttribute{
					Required:  true,
					Sensitive: true,
				},
			},
		},
		"kandji_api_token": schema.SingleNestedAttribute{
			MarkdownDescription: "Secret for a `" + string(mondoov1.CredentialV2KindKandjiApiToken) + "` credential.",
			Optional:            true,
			Attributes: map[string]schema.Attribute{
				"api_url": schema.StringAttribute{
					Required:  true,
					Sensitive: true,
				},
				"api_token": schema.StringAttribute{
					Required:  true,
					Sensitive: true,
				},
			},
		},
		"openvas_cloud": schema.SingleNestedAttribute{
			MarkdownDescription: "Secret for a `" + string(mondoov1.CredentialV2KindOpenvasCloud) + "` credential.",
			Optional:            true,
			Attributes: map[string]schema.Attribute{
				"api_token": schema.StringAttribute{
					Required:  true,
					Sensitive: true,
				},
				"base_url": schema.StringAttribute{
					Optional:  true,
					Sensitive: true,
				},
			},
		},
		"sentinelone": schema.SingleNestedAttribute{
			MarkdownDescription: "Secret for a `" + string(mondoov1.CredentialV2KindSentinelone) + "` credential.",
			Optional:            true,
			Attributes: map[string]schema.Attribute{
				"host": schema.StringAttribute{
					Required:  true,
					Sensitive: true,
				},
				"api_token": schema.StringAttribute{
					Required:  true,
					Sensitive: true,
				},
			},
		},
	}
}

// credentialSecretPaths returns the ExactlyOneOf path set. It is generated from
// the SDK type, so it is total by construction rather than by maintenance.
func credentialSecretPaths() []path.Expression {
	return []path.Expression{
		path.MatchRoot("github_pat"),
		path.MatchRoot("github_app"),
		path.MatchRoot("slack"),
		path.MatchRoot("aws"),
		path.MatchRoot("crowdstrike"),
		path.MatchRoot("anthropic"),
		path.MatchRoot("sprites_token"),
		path.MatchRoot("sprites_fly_macaroon"),
		path.MatchRoot("shodan_api_key"),
		path.MatchRoot("cloudflare_api_token"),
		path.MatchRoot("hetzner_api_token"),
		path.MatchRoot("digitalocean_api_token"),
		path.MatchRoot("vercel_api_token"),
		path.MatchRoot("okta_api_token"),
		path.MatchRoot("gitlab_token"),
		path.MatchRoot("entra_client_secret"),
		path.MatchRoot("entra_certificate"),
		path.MatchRoot("gcp_service_account"),
		path.MatchRoot("nextdns_api_key"),
		path.MatchRoot("tailscale_api_key"),
		path.MatchRoot("tailscale_oauth_client"),
		path.MatchRoot("stackit_service_account_key"),
		path.MatchRoot("mongodb_atlas"),
		path.MatchRoot("databricks_oauth"),
		path.MatchRoot("oci_api_key"),
		path.MatchRoot("snowflake_keypair"),
		path.MatchRoot("jira"),
		path.MatchRoot("zendesk"),
		path.MatchRoot("jamf_oauth"),
		path.MatchRoot("tenable_io"),
		path.MatchRoot("snyk_api_token"),
		path.MatchRoot("sonarqube_token"),
		path.MatchRoot("elastic_api_key"),
		path.MatchRoot("s3_access_key"),
		path.MatchRoot("tenable_sc"),
		path.MatchRoot("qualys"),
		path.MatchRoot("security_scorecard"),
		path.MatchRoot("jfrog_access_token"),
		path.MatchRoot("azure_blob_sas"),
		path.MatchRoot("snowflake_password"),
		path.MatchRoot("splunk_hec_token"),
		path.MatchRoot("kandji_api_token"),
		path.MatchRoot("openvas_cloud"),
		path.MatchRoot("sentinelone"),
	}
}

// BuildSecretInput builds the secret input from whichever kind attribute is
// set. Every field of that arm is sent, every time: rotateCredentialV2 replaces
// the whole payload rather than merging it, so an omitted baseUrl resets a
// GitHub Enterprise credential to github.com and an omitted region resets AWS
// to us-east-1.
func (m *credentialResourceModel) BuildSecretInput() (mondoov1.CredentialV2SecretInput, error) {
	var (
		in  mondoov1.CredentialV2SecretInput
		set int
	)

	if m.GithubPat != nil {
		set++
		in.GithubPat = &mondoov1.GithubPatCredentialV2Input{
			Token:   mondoov1.String(m.GithubPat.Token.ValueString()),
			BaseUrl: credentialOptionalString(m.GithubPat.BaseUrl),
		}
	}

	if m.GithubApp != nil {
		set++
		in.GithubApp = &mondoov1.GithubAppCredentialV2Input{
			AppId:      mondoov1.String(m.GithubApp.AppId.ValueString()),
			PrivateKey: mondoov1.String(m.GithubApp.PrivateKey.ValueString()),
		}
	}

	if m.Slack != nil {
		set++
		in.Slack = &mondoov1.SlackCredentialV2Input{
			BotToken: mondoov1.String(m.Slack.BotToken.ValueString()),
		}
	}

	if m.Aws != nil {
		set++
		in.Aws = &mondoov1.AwsCredentialV2Input{
			AccessKeyId:     mondoov1.String(m.Aws.AccessKeyId.ValueString()),
			SecretAccessKey: mondoov1.String(m.Aws.SecretAccessKey.ValueString()),
			Region:          credentialOptionalString(m.Aws.Region),
		}
	}

	if m.Crowdstrike != nil {
		set++
		in.Crowdstrike = &mondoov1.CrowdstrikeCredentialV2Input{
			ClientId:     mondoov1.String(m.Crowdstrike.ClientId.ValueString()),
			ClientSecret: mondoov1.String(m.Crowdstrike.ClientSecret.ValueString()),
			BaseUrl:      credentialOptionalString(m.Crowdstrike.BaseUrl),
		}
	}

	if m.Anthropic != nil {
		set++
		in.Anthropic = &mondoov1.AnthropicCredentialV2Input{
			ApiKey: mondoov1.String(m.Anthropic.ApiKey.ValueString()),
		}
	}

	if m.SpritesToken != nil {
		set++
		in.SpritesToken = &mondoov1.SpritesTokenCredentialV2Input{
			Token:   mondoov1.String(m.SpritesToken.Token.ValueString()),
			BaseUrl: credentialOptionalString(m.SpritesToken.BaseUrl),
		}
	}

	if m.SpritesFlyMacaroon != nil {
		set++
		in.SpritesFlyMacaroon = &mondoov1.SpritesFlyMacaroonCredentialV2Input{
			Macaroon: mondoov1.String(m.SpritesFlyMacaroon.Macaroon.ValueString()),
			Org:      credentialOptionalString(m.SpritesFlyMacaroon.Org),
			BaseUrl:  credentialOptionalString(m.SpritesFlyMacaroon.BaseUrl),
		}
	}

	if m.ShodanApiKey != nil {
		set++
		in.ShodanApiKey = &mondoov1.ShodanApiKeyCredentialV2Input{
			ApiKey: mondoov1.String(m.ShodanApiKey.ApiKey.ValueString()),
		}
	}

	if m.CloudflareApiToken != nil {
		set++
		in.CloudflareApiToken = &mondoov1.CloudflareApiTokenCredentialV2Input{
			ApiToken: mondoov1.String(m.CloudflareApiToken.ApiToken.ValueString()),
		}
	}

	if m.HetznerApiToken != nil {
		set++
		in.HetznerApiToken = &mondoov1.HetznerApiTokenCredentialV2Input{
			ApiToken: mondoov1.String(m.HetznerApiToken.ApiToken.ValueString()),
		}
	}

	if m.DigitaloceanApiToken != nil {
		set++
		in.DigitaloceanApiToken = &mondoov1.DigitaloceanApiTokenCredentialV2Input{
			ApiToken: mondoov1.String(m.DigitaloceanApiToken.ApiToken.ValueString()),
		}
	}

	if m.VercelApiToken != nil {
		set++
		in.VercelApiToken = &mondoov1.VercelApiTokenCredentialV2Input{
			ApiToken: mondoov1.String(m.VercelApiToken.ApiToken.ValueString()),
		}
	}

	if m.OktaApiToken != nil {
		set++
		in.OktaApiToken = &mondoov1.OktaApiTokenCredentialV2Input{
			Domain:   mondoov1.String(m.OktaApiToken.Domain.ValueString()),
			ApiToken: mondoov1.String(m.OktaApiToken.ApiToken.ValueString()),
		}
	}

	if m.GitlabToken != nil {
		set++
		in.GitlabToken = &mondoov1.GitlabTokenCredentialV2Input{
			Token:   mondoov1.String(m.GitlabToken.Token.ValueString()),
			BaseUrl: credentialOptionalString(m.GitlabToken.BaseUrl),
		}
	}

	if m.EntraClientSecret != nil {
		set++
		in.EntraClientSecret = &mondoov1.EntraClientSecretCredentialV2Input{
			TenantId:     mondoov1.String(m.EntraClientSecret.TenantId.ValueString()),
			ClientId:     mondoov1.String(m.EntraClientSecret.ClientId.ValueString()),
			ClientSecret: mondoov1.String(m.EntraClientSecret.ClientSecret.ValueString()),
		}
	}

	if m.EntraCertificate != nil {
		set++
		in.EntraCertificate = &mondoov1.EntraCertificateCredentialV2Input{
			TenantId:    mondoov1.String(m.EntraCertificate.TenantId.ValueString()),
			ClientId:    mondoov1.String(m.EntraCertificate.ClientId.ValueString()),
			Certificate: mondoov1.String(m.EntraCertificate.Certificate.ValueString()),
		}
	}

	if m.GcpServiceAccount != nil {
		set++
		in.GcpServiceAccount = &mondoov1.GcpServiceAccountCredentialV2Input{
			CredentialsJson: mondoov1.String(m.GcpServiceAccount.CredentialsJson.ValueString()),
		}
	}

	if m.NextdnsApiKey != nil {
		set++
		in.NextdnsApiKey = &mondoov1.NextdnsApiKeyCredentialV2Input{
			ApiKey: mondoov1.String(m.NextdnsApiKey.ApiKey.ValueString()),
		}
	}

	if m.TailscaleApiKey != nil {
		set++
		in.TailscaleApiKey = &mondoov1.TailscaleApiKeyCredentialV2Input{
			ApiKey: mondoov1.String(m.TailscaleApiKey.ApiKey.ValueString()),
		}
	}

	if m.TailscaleOauthClient != nil {
		set++
		in.TailscaleOauthClient = &mondoov1.TailscaleOauthClientCredentialV2Input{
			ClientId:     mondoov1.String(m.TailscaleOauthClient.ClientId.ValueString()),
			ClientSecret: mondoov1.String(m.TailscaleOauthClient.ClientSecret.ValueString()),
		}
	}

	if m.StackitServiceAccountKey != nil {
		set++
		in.StackitServiceAccountKey = &mondoov1.StackitServiceAccountKeyCredentialV2Input{
			ServiceAccountKey: mondoov1.String(m.StackitServiceAccountKey.ServiceAccountKey.ValueString()),
		}
	}

	if m.MongodbAtlas != nil {
		set++
		in.MongodbAtlas = &mondoov1.MongodbAtlasCredentialV2Input{
			PublicKey:  mondoov1.String(m.MongodbAtlas.PublicKey.ValueString()),
			PrivateKey: mondoov1.String(m.MongodbAtlas.PrivateKey.ValueString()),
		}
	}

	if m.DatabricksOauth != nil {
		set++
		in.DatabricksOauth = &mondoov1.DatabricksOauthCredentialV2Input{
			Host:         mondoov1.String(m.DatabricksOauth.Host.ValueString()),
			ClientId:     mondoov1.String(m.DatabricksOauth.ClientId.ValueString()),
			ClientSecret: mondoov1.String(m.DatabricksOauth.ClientSecret.ValueString()),
		}
	}

	if m.OciApiKey != nil {
		set++
		in.OciApiKey = &mondoov1.OciApiKeyCredentialV2Input{
			TenancyOcid: mondoov1.String(m.OciApiKey.TenancyOcid.ValueString()),
			UserOcid:    mondoov1.String(m.OciApiKey.UserOcid.ValueString()),
			Region:      mondoov1.String(m.OciApiKey.Region.ValueString()),
			Fingerprint: mondoov1.String(m.OciApiKey.Fingerprint.ValueString()),
			PrivateKey:  mondoov1.String(m.OciApiKey.PrivateKey.ValueString()),
		}
	}

	if m.SnowflakeKeypair != nil {
		set++
		in.SnowflakeKeypair = &mondoov1.SnowflakeKeypairCredentialV2Input{
			Account:    mondoov1.String(m.SnowflakeKeypair.Account.ValueString()),
			User:       mondoov1.String(m.SnowflakeKeypair.User.ValueString()),
			PrivateKey: mondoov1.String(m.SnowflakeKeypair.PrivateKey.ValueString()),
		}
	}

	if m.Jira != nil {
		set++
		in.Jira = &mondoov1.JiraCredentialV2Input{
			Host:     mondoov1.String(m.Jira.Host.ValueString()),
			Email:    mondoov1.String(m.Jira.Email.ValueString()),
			ApiToken: mondoov1.String(m.Jira.ApiToken.ValueString()),
			CloudId:  credentialOptionalString(m.Jira.CloudId),
		}
	}

	if m.Zendesk != nil {
		set++
		in.Zendesk = &mondoov1.ZendeskCredentialV2Input{
			Subdomain: mondoov1.String(m.Zendesk.Subdomain.ValueString()),
			Email:     mondoov1.String(m.Zendesk.Email.ValueString()),
			ApiToken:  mondoov1.String(m.Zendesk.ApiToken.ValueString()),
		}
	}

	if m.JamfOauth != nil {
		set++
		in.JamfOauth = &mondoov1.JamfOauthCredentialV2Input{
			BaseUrl:      mondoov1.String(m.JamfOauth.BaseUrl.ValueString()),
			ClientId:     mondoov1.String(m.JamfOauth.ClientId.ValueString()),
			ClientSecret: mondoov1.String(m.JamfOauth.ClientSecret.ValueString()),
		}
	}

	if m.TenableIo != nil {
		set++
		in.TenableIo = &mondoov1.TenableIoCredentialV2Input{
			AccessKey: mondoov1.String(m.TenableIo.AccessKey.ValueString()),
			SecretKey: mondoov1.String(m.TenableIo.SecretKey.ValueString()),
			BaseUrl:   credentialOptionalString(m.TenableIo.BaseUrl),
		}
	}

	if m.SnykApiToken != nil {
		set++
		in.SnykApiToken = &mondoov1.SnykApiTokenCredentialV2Input{
			ApiToken: mondoov1.String(m.SnykApiToken.ApiToken.ValueString()),
			BaseUrl:  credentialOptionalString(m.SnykApiToken.BaseUrl),
		}
	}

	if m.SonarqubeToken != nil {
		set++
		in.SonarqubeToken = &mondoov1.SonarqubeTokenCredentialV2Input{
			Token:   mondoov1.String(m.SonarqubeToken.Token.ValueString()),
			BaseUrl: credentialOptionalString(m.SonarqubeToken.BaseUrl),
		}
	}

	if m.ElasticApiKey != nil {
		set++
		in.ElasticApiKey = &mondoov1.ElasticApiKeyCredentialV2Input{
			ApiKey:   mondoov1.String(m.ElasticApiKey.ApiKey.ValueString()),
			Endpoint: credentialOptionalString(m.ElasticApiKey.Endpoint),
			CloudId:  credentialOptionalString(m.ElasticApiKey.CloudId),
		}
	}

	if m.S3AccessKey != nil {
		set++
		in.S3AccessKey = &mondoov1.S3AccessKeyCredentialV2Input{
			Endpoint:        mondoov1.String(m.S3AccessKey.Endpoint.ValueString()),
			AccessKeyId:     mondoov1.String(m.S3AccessKey.AccessKeyId.ValueString()),
			SecretAccessKey: mondoov1.String(m.S3AccessKey.SecretAccessKey.ValueString()),
			Region:          credentialOptionalString(m.S3AccessKey.Region),
		}
	}

	if m.TenableSc != nil {
		set++
		in.TenableSc = &mondoov1.TenableScCredentialV2Input{
			ServerUrl: mondoov1.String(m.TenableSc.ServerUrl.ValueString()),
			AccessKey: mondoov1.String(m.TenableSc.AccessKey.ValueString()),
			SecretKey: mondoov1.String(m.TenableSc.SecretKey.ValueString()),
		}
	}

	if m.Qualys != nil {
		set++
		in.Qualys = &mondoov1.QualysCredentialV2Input{
			BaseUrl:  mondoov1.String(m.Qualys.BaseUrl.ValueString()),
			Username: mondoov1.String(m.Qualys.Username.ValueString()),
			Password: mondoov1.String(m.Qualys.Password.ValueString()),
		}
	}

	if m.SecurityScorecard != nil {
		set++
		in.SecurityScorecard = &mondoov1.SecurityScorecardCredentialV2Input{
			ApiToken: mondoov1.String(m.SecurityScorecard.ApiToken.ValueString()),
		}
	}

	if m.JfrogAccessToken != nil {
		set++
		in.JfrogAccessToken = &mondoov1.JfrogAccessTokenCredentialV2Input{
			BaseUrl:     mondoov1.String(m.JfrogAccessToken.BaseUrl.ValueString()),
			AccessToken: mondoov1.String(m.JfrogAccessToken.AccessToken.ValueString()),
		}
	}

	if m.AzureBlobSas != nil {
		set++
		in.AzureBlobSas = &mondoov1.AzureBlobSasCredentialV2Input{
			SasUrl: mondoov1.String(m.AzureBlobSas.SasUrl.ValueString()),
		}
	}

	if m.SnowflakePassword != nil {
		set++
		in.SnowflakePassword = &mondoov1.SnowflakePasswordCredentialV2Input{
			Account:  mondoov1.String(m.SnowflakePassword.Account.ValueString()),
			User:     mondoov1.String(m.SnowflakePassword.User.ValueString()),
			Password: mondoov1.String(m.SnowflakePassword.Password.ValueString()),
		}
	}

	if m.SplunkHecToken != nil {
		set++
		in.SplunkHecToken = &mondoov1.SplunkHecTokenCredentialV2Input{
			Host:  mondoov1.String(m.SplunkHecToken.Host.ValueString()),
			Token: mondoov1.String(m.SplunkHecToken.Token.ValueString()),
		}
	}

	if m.KandjiApiToken != nil {
		set++
		in.KandjiApiToken = &mondoov1.KandjiApiTokenCredentialV2Input{
			ApiUrl:   mondoov1.String(m.KandjiApiToken.ApiUrl.ValueString()),
			ApiToken: mondoov1.String(m.KandjiApiToken.ApiToken.ValueString()),
		}
	}

	if m.OpenvasCloud != nil {
		set++
		in.OpenvasCloud = &mondoov1.OpenvasCloudCredentialV2Input{
			ApiToken: mondoov1.String(m.OpenvasCloud.ApiToken.ValueString()),
			BaseUrl:  credentialOptionalString(m.OpenvasCloud.BaseUrl),
		}
	}

	if m.Sentinelone != nil {
		set++
		in.Sentinelone = &mondoov1.SentineloneCredentialV2Input{
			Host:     mondoov1.String(m.Sentinelone.Host.ValueString()),
			ApiToken: mondoov1.String(m.Sentinelone.ApiToken.ValueString()),
		}
	}

	if set != 1 {
		return in, fmt.Errorf("exactly one credential kind attribute must be set, found %d", set)
	}
	return in, nil
}

// SecretKind reports the kind implied by whichever attribute is set.
func (m *credentialResourceModel) SecretKind() (mondoov1.CredentialV2Kind, error) {
	var (
		kind mondoov1.CredentialV2Kind
		set  int
	)

	if m.GithubPat != nil {
		set++
		kind = mondoov1.CredentialV2KindGithubPat
	}

	if m.GithubApp != nil {
		set++
		kind = mondoov1.CredentialV2KindGithubApp
	}

	if m.Slack != nil {
		set++
		kind = mondoov1.CredentialV2KindSlack
	}

	if m.Aws != nil {
		set++
		kind = mondoov1.CredentialV2KindAws
	}

	if m.Crowdstrike != nil {
		set++
		kind = mondoov1.CredentialV2KindCrowdstrike
	}

	if m.Anthropic != nil {
		set++
		kind = mondoov1.CredentialV2KindAnthropic
	}

	if m.SpritesToken != nil {
		set++
		kind = mondoov1.CredentialV2KindSpritesToken
	}

	if m.SpritesFlyMacaroon != nil {
		set++
		kind = mondoov1.CredentialV2KindSpritesFlyMacaroon
	}

	if m.ShodanApiKey != nil {
		set++
		kind = mondoov1.CredentialV2KindShodanApiKey
	}

	if m.CloudflareApiToken != nil {
		set++
		kind = mondoov1.CredentialV2KindCloudflareApiToken
	}

	if m.HetznerApiToken != nil {
		set++
		kind = mondoov1.CredentialV2KindHetznerApiToken
	}

	if m.DigitaloceanApiToken != nil {
		set++
		kind = mondoov1.CredentialV2KindDigitaloceanApiToken
	}

	if m.VercelApiToken != nil {
		set++
		kind = mondoov1.CredentialV2KindVercelApiToken
	}

	if m.OktaApiToken != nil {
		set++
		kind = mondoov1.CredentialV2KindOktaApiToken
	}

	if m.GitlabToken != nil {
		set++
		kind = mondoov1.CredentialV2KindGitlabToken
	}

	if m.EntraClientSecret != nil {
		set++
		kind = mondoov1.CredentialV2KindEntraClientSecret
	}

	if m.EntraCertificate != nil {
		set++
		kind = mondoov1.CredentialV2KindEntraCertificate
	}

	if m.GcpServiceAccount != nil {
		set++
		kind = mondoov1.CredentialV2KindGcpServiceAccount
	}

	if m.NextdnsApiKey != nil {
		set++
		kind = mondoov1.CredentialV2KindNextdnsApiKey
	}

	if m.TailscaleApiKey != nil {
		set++
		kind = mondoov1.CredentialV2KindTailscaleApiKey
	}

	if m.TailscaleOauthClient != nil {
		set++
		kind = mondoov1.CredentialV2KindTailscaleOauthClient
	}

	if m.StackitServiceAccountKey != nil {
		set++
		kind = mondoov1.CredentialV2KindStackitServiceAccountKey
	}

	if m.MongodbAtlas != nil {
		set++
		kind = mondoov1.CredentialV2KindMongodbAtlas
	}

	if m.DatabricksOauth != nil {
		set++
		kind = mondoov1.CredentialV2KindDatabricksOauth
	}

	if m.OciApiKey != nil {
		set++
		kind = mondoov1.CredentialV2KindOciApiKey
	}

	if m.SnowflakeKeypair != nil {
		set++
		kind = mondoov1.CredentialV2KindSnowflakeKeypair
	}

	if m.Jira != nil {
		set++
		kind = mondoov1.CredentialV2KindJira
	}

	if m.Zendesk != nil {
		set++
		kind = mondoov1.CredentialV2KindZendesk
	}

	if m.JamfOauth != nil {
		set++
		kind = mondoov1.CredentialV2KindJamfOauth
	}

	if m.TenableIo != nil {
		set++
		kind = mondoov1.CredentialV2KindTenableIo
	}

	if m.SnykApiToken != nil {
		set++
		kind = mondoov1.CredentialV2KindSnykApiToken
	}

	if m.SonarqubeToken != nil {
		set++
		kind = mondoov1.CredentialV2KindSonarqubeToken
	}

	if m.ElasticApiKey != nil {
		set++
		kind = mondoov1.CredentialV2KindElasticApiKey
	}

	if m.S3AccessKey != nil {
		set++
		kind = mondoov1.CredentialV2KindS3AccessKey
	}

	if m.TenableSc != nil {
		set++
		kind = mondoov1.CredentialV2KindTenableSc
	}

	if m.Qualys != nil {
		set++
		kind = mondoov1.CredentialV2KindQualys
	}

	if m.SecurityScorecard != nil {
		set++
		kind = mondoov1.CredentialV2KindSecurityScorecard
	}

	if m.JfrogAccessToken != nil {
		set++
		kind = mondoov1.CredentialV2KindJfrogAccessToken
	}

	if m.AzureBlobSas != nil {
		set++
		kind = mondoov1.CredentialV2KindAzureBlobSas
	}

	if m.SnowflakePassword != nil {
		set++
		kind = mondoov1.CredentialV2KindSnowflakePassword
	}

	if m.SplunkHecToken != nil {
		set++
		kind = mondoov1.CredentialV2KindSplunkHecToken
	}

	if m.KandjiApiToken != nil {
		set++
		kind = mondoov1.CredentialV2KindKandjiApiToken
	}

	if m.OpenvasCloud != nil {
		set++
		kind = mondoov1.CredentialV2KindOpenvasCloud
	}

	if m.Sentinelone != nil {
		set++
		kind = mondoov1.CredentialV2KindSentinelone
	}

	if set != 1 {
		return kind, fmt.Errorf("exactly one credential kind attribute must be set, found %d", set)
	}
	return kind, nil
}
