// Copyright (c) Mondoo, Inc.
// SPDX-License-Identifier: BUSL-1.1
//
// Code generated by gen.go; DO NOT EDIT.

package provider

import (
	"fmt"
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
)

func TestAccGoogleWorkspaceIntegrationResource(t *testing.T) {
	resource.Test(t, resource.TestCase{
		PreCheck:                 func() { testAccPreCheck(t) },
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			// Create and Read testing
			{
				Config: testAccGoogleWorkspaceIntegrationResourceConfig(accSpace.ID(), "one", "CustomerId_1", "ImpersonatedUserEmail_1", "ServiceAccount_1"),
				Check: resource.ComposeAggregateTestCheckFunc(
					resource.TestCheckResourceAttr("mondoo_integration_google_workspace.test", "name", "one"),
					resource.TestCheckResourceAttr("mondoo_integration_google_workspace.test", "space_id", accSpace.ID()),
				),
			},
			{
				Config: testAccGoogleWorkspaceIntegrationResourceWithSpaceInProviderConfig(accSpace.ID(), "two", "CustomerId_1", "ImpersonatedUserEmail_1", "ServiceAccount_1"),
				Check: resource.ComposeAggregateTestCheckFunc(
					resource.TestCheckResourceAttr("mondoo_integration_google_workspace.test", "name", "two"),
					resource.TestCheckResourceAttr("mondoo_integration_google_workspace.test", "space_id", accSpace.ID()),
				),
			},
			// Update and Read testing
			{
				Config: testAccGoogleWorkspaceIntegrationResourceConfig(accSpace.ID(), "three", "CustomerId_2", "ImpersonatedUserEmail_2", "ServiceAccount_2"),
				Check: resource.ComposeAggregateTestCheckFunc(
					resource.TestCheckResourceAttr("mondoo_integration_google_workspace.test", "name", "three"),
					resource.TestCheckResourceAttr("mondoo_integration_google_workspace.test", "space_id", accSpace.ID()),
				),
			},
			{
				Config: testAccGoogleWorkspaceIntegrationResourceWithSpaceInProviderConfig(accSpace.ID(), "four", "CustomerId_2", "ImpersonatedUserEmail_2", "ServiceAccount_2"),
				Check: resource.ComposeAggregateTestCheckFunc(
					resource.TestCheckResourceAttr("mondoo_integration_google_workspace.test", "name", "four"),
					resource.TestCheckResourceAttr("mondoo_integration_google_workspace.test", "space_id", accSpace.ID()),
				),
			},
			// Delete testing automatically occurs in TestCase
		},
	})
}

func testAccGoogleWorkspaceIntegrationResourceConfig(spaceID string, intName string, customer_id string, impersonated_user_email string, service_account string) string {
	return fmt.Sprintf(`
resource "mondoo_integration_google_workspace" "test" {
  space_id      = %q
  name          = %q
  customer_id = %q
  impersonated_user_email = %q
  service_account = %q
}
`, spaceID, intName, customer_id, impersonated_user_email, service_account,
	)
}

func testAccGoogleWorkspaceIntegrationResourceWithSpaceInProviderConfig(spaceID string, intName string, customer_id string, impersonated_user_email string, service_account string) string {
	return fmt.Sprintf(`
provider "mondoo" {
  space = %q
}
resource "mondoo_integration_google_workspace" "test" {
  name          = %q
  customer_id = %q
  impersonated_user_email = %q
  service_account = %q
}
`, spaceID, intName, customer_id, impersonated_user_email, service_account,
	)
}
