// Copyright (c) Mondoo, Inc.
// SPDX-License-Identifier: BUSL-1.1
//
// Code generated by gen.go; DO NOT EDIT.

package provider

import (
	"fmt"
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
)

func TestAccAzureDevOpsIntegrationResource(t *testing.T) {
	resource.Test(t, resource.TestCase{
		PreCheck:                 func() { testAccPreCheck(t) },
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			// Create and Read testing
			{
				Config: testAccAzureDevOpsIntegrationResourceConfig(accSpace.ID(), "one"),
				Check: resource.ComposeAggregateTestCheckFunc(
					resource.TestCheckResourceAttr("mondoo_integration_azure_dev_ops.test", "name", "one"),
					resource.TestCheckResourceAttr("mondoo_integration_azure_dev_ops.test", "space_id", accSpace.ID()),
				),
			},
			{
				Config: testAccAzureDevOpsIntegrationResourceWithSpaceInProviderConfig(accSpace.ID(), "two"),
				Check: resource.ComposeAggregateTestCheckFunc(
					resource.TestCheckResourceAttr("mondoo_integration_azure_dev_ops.test", "name", "two"),
					resource.TestCheckResourceAttr("mondoo_integration_azure_dev_ops.test", "space_id", accSpace.ID()),
				),
			},
			// Update and Read testing
			{
				Config: testAccAzureDevOpsIntegrationResourceConfig(accSpace.ID(), "three"),
				Check: resource.ComposeAggregateTestCheckFunc(
					resource.TestCheckResourceAttr("mondoo_integration_azure_dev_ops.test", "name", "three"),
					resource.TestCheckResourceAttr("mondoo_integration_azure_dev_ops.test", "space_id", accSpace.ID()),
				),
			},
			{
				Config: testAccAzureDevOpsIntegrationResourceWithSpaceInProviderConfig(accSpace.ID(), "four"),
				Check: resource.ComposeAggregateTestCheckFunc(
					resource.TestCheckResourceAttr("mondoo_integration_azure_dev_ops.test", "name", "four"),
					resource.TestCheckResourceAttr("mondoo_integration_azure_dev_ops.test", "space_id", accSpace.ID()),
				),
			},
			// Delete testing automatically occurs in TestCase
		},
	})
}

func testAccAzureDevOpsIntegrationResourceConfig(spaceID, intName string) string {
	return fmt.Sprintf(`
resource "mondoo_integration_azure_dev_ops" "test" {
  space_id      = %[1]q
  name          = %[2]q
}
`, spaceID, intName)
}

func testAccAzureDevOpsIntegrationResourceWithSpaceInProviderConfig(spaceID, intName string) string {
	return fmt.Sprintf(`
provider "mondoo" {
  space = %[1]q
}
resource "mondoo_integration_azure_dev_ops" "test" {
  name          = %[2]q
}
`, spaceID, intName)
}
