// Copyright (c) Mondoo, Inc.
// SPDX-License-Identifier: BUSL-1.1
//
// Code generated by gen.go; DO NOT EDIT.

package provider

import (
	"fmt"
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
)

func TestAccOktaIntegrationResource(t *testing.T) {
	resource.Test(t, resource.TestCase{
		PreCheck:                 func() { testAccPreCheck(t) },
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			// Create and Read testing
			{
				Config: testAccOktaIntegrationResourceConfig(accSpace.ID(), "one", "CredentialMrn_1", "Organization_1", "Token_1"),
				Check: resource.ComposeAggregateTestCheckFunc(
					resource.TestCheckResourceAttr("mondoo_integration_okta.test", "name", "one"),
					resource.TestCheckResourceAttr("mondoo_integration_okta.test", "space_id", accSpace.ID()),
				),
			},
			{
				Config: testAccOktaIntegrationResourceWithSpaceInProviderConfig(accSpace.ID(), "two", "CredentialMrn_1", "Organization_1", "Token_1"),
				Check: resource.ComposeAggregateTestCheckFunc(
					resource.TestCheckResourceAttr("mondoo_integration_okta.test", "name", "two"),
					resource.TestCheckResourceAttr("mondoo_integration_okta.test", "space_id", accSpace.ID()),
				),
			},
			// Update and Read testing
			{
				Config: testAccOktaIntegrationResourceConfig(accSpace.ID(), "three", "CredentialMrn_2", "Organization_2", "Token_2"),
				Check: resource.ComposeAggregateTestCheckFunc(
					resource.TestCheckResourceAttr("mondoo_integration_okta.test", "name", "three"),
					resource.TestCheckResourceAttr("mondoo_integration_okta.test", "space_id", accSpace.ID()),
				),
			},
			{
				Config: testAccOktaIntegrationResourceWithSpaceInProviderConfig(accSpace.ID(), "four", "CredentialMrn_2", "Organization_2", "Token_2"),
				Check: resource.ComposeAggregateTestCheckFunc(
					resource.TestCheckResourceAttr("mondoo_integration_okta.test", "name", "four"),
					resource.TestCheckResourceAttr("mondoo_integration_okta.test", "space_id", accSpace.ID()),
				),
			},
			// Delete testing automatically occurs in TestCase
		},
	})
}

func testAccOktaIntegrationResourceConfig(spaceID string, intName string, credential_mrn string, organization string, token string) string {
	return fmt.Sprintf(`
resource "mondoo_integration_okta" "test" {
  space_id      = %q
  name          = %q
  credential_mrn = %q
  organization = %q
  token = %q
}
`, spaceID, intName, credential_mrn, organization, token,
	)
}

func testAccOktaIntegrationResourceWithSpaceInProviderConfig(spaceID string, intName string, credential_mrn string, organization string, token string) string {
	return fmt.Sprintf(`
provider "mondoo" {
  space = %q
}
resource "mondoo_integration_okta" "test" {
  name          = %q
  credential_mrn = %q
  organization = %q
  token = %q
}
`, spaceID, intName, credential_mrn, organization, token,
	)
}
