// Copyright (c) Mondoo, Inc.
// SPDX-License-Identifier: BUSL-1.1
//
// Code generated by gen.go; DO NOT EDIT.

package provider

import (
	"fmt"
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
)

func TestAccAzureDevopsIntegrationResource(t *testing.T) {
	resource.Test(t, resource.TestCase{
		PreCheck:                 func() { testAccPreCheck(t) },
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			// Create and Read testing
			{
				Config: testAccAzureDevopsIntegrationResourceConfig(accSpace.ID(), "one", false, false, "ClientSecret_1", "DefaultProjectName_1", "OrganizationUrl_1", "ServicePrincipalId_1", "TenantId_1"),
				Check: resource.ComposeAggregateTestCheckFunc(
					resource.TestCheckResourceAttr("mondoo_integration_azure_devops.test", "name", "one"),
					resource.TestCheckResourceAttr("mondoo_integration_azure_devops.test", "space_id", accSpace.ID()),
				),
			},
			{
				Config: testAccAzureDevopsIntegrationResourceWithSpaceInProviderConfig(accSpace.ID(), "two", false, false, "ClientSecret_1", "DefaultProjectName_1", "OrganizationUrl_1", "ServicePrincipalId_1", "TenantId_1"),
				Check: resource.ComposeAggregateTestCheckFunc(
					resource.TestCheckResourceAttr("mondoo_integration_azure_devops.test", "name", "two"),
					resource.TestCheckResourceAttr("mondoo_integration_azure_devops.test", "space_id", accSpace.ID()),
				),
			},
			// Update and Read testing
			{
				Config: testAccAzureDevopsIntegrationResourceConfig(accSpace.ID(), "three", true, true, "ClientSecret_2", "DefaultProjectName_2", "OrganizationUrl_2", "ServicePrincipalId_2", "TenantId_2"),
				Check: resource.ComposeAggregateTestCheckFunc(
					resource.TestCheckResourceAttr("mondoo_integration_azure_devops.test", "name", "three"),
					resource.TestCheckResourceAttr("mondoo_integration_azure_devops.test", "space_id", accSpace.ID()),
				),
			},
			{
				Config: testAccAzureDevopsIntegrationResourceWithSpaceInProviderConfig(accSpace.ID(), "four", true, true, "ClientSecret_2", "DefaultProjectName_2", "OrganizationUrl_2", "ServicePrincipalId_2", "TenantId_2"),
				Check: resource.ComposeAggregateTestCheckFunc(
					resource.TestCheckResourceAttr("mondoo_integration_azure_devops.test", "name", "four"),
					resource.TestCheckResourceAttr("mondoo_integration_azure_devops.test", "space_id", accSpace.ID()),
				),
			},
			// Delete testing automatically occurs in TestCase
		},
	})
}

func testAccAzureDevopsIntegrationResourceConfig(spaceID string, intName string, auto_close_tickets bool, auto_create_tickets bool, client_secret string, default_project_name string, organization_url string, service_principal_id string, tenant_id string) string {
	return fmt.Sprintf(`
resource "mondoo_integration_azure_devops" "test" {
  space_id      = %q
  name          = %q
  auto_close_tickets = %t
  auto_create_tickets = %t
  client_secret = %q
  default_project_name = %q
  organization_url = %q
  service_principal_id = %q
  tenant_id = %q
}
`, spaceID, intName, auto_close_tickets, auto_create_tickets, client_secret, default_project_name, organization_url, service_principal_id, tenant_id,
	)
}

func testAccAzureDevopsIntegrationResourceWithSpaceInProviderConfig(spaceID string, intName string, auto_close_tickets bool, auto_create_tickets bool, client_secret string, default_project_name string, organization_url string, service_principal_id string, tenant_id string) string {
	return fmt.Sprintf(`
provider "mondoo" {
  space = %q
}
resource "mondoo_integration_azure_devops" "test" {
  name          = %q
  auto_close_tickets = %t
  auto_create_tickets = %t
  client_secret = %q
  default_project_name = %q
  organization_url = %q
  service_principal_id = %q
  tenant_id = %q
}
`, spaceID, intName, auto_close_tickets, auto_create_tickets, client_secret, default_project_name, organization_url, service_principal_id, tenant_id,
	)
}
