// Copyright (c) Mondoo, Inc.
// SPDX-License-Identifier: BUSL-1.1

package provider

import "github.com/hashicorp/terraform-plugin-framework/resource"

var autoGeneratedResources = []func() resource.Resource{
	NewIntegrationAzureResource,
	NewIntegrationAwsResource,
	NewIntegrationAwsServerlessResource,
	NewIntegrationDomainResource,
	NewIntegrationGcpResource,
	NewIntegrationOciTenantResource,
	NewIntegrationSlackResource,
	NewIntegrationMs365Resource,
	NewIntegrationGithubResource,
	NewIntegrationShodanResource,
	NewIntegrationZendeskResource,
	NewIntegrationJiraResource,
	NewIntegrationEmailResource,
	NewIntegrationGitlabResource,
	NewIntegrationMsDefenderResource,
	NewIntegrationCrowdstrikeResource,
	NewIntegrationSentinelOneResource,
	// Auto-generated resources
	NewIntegrationAzureDevopsResource,
	NewIntegrationOktaResource,
	NewIntegrationGoogleWorkspaceResource,
}
