// Copyright (c) Mondoo, Inc.
// SPDX-License-Identifier: BUSL-1.1
//
// Code generated by gen.go; DO NOT EDIT.

package provider

import "github.com/hashicorp/terraform-plugin-framework/resource"

var autoGeneratedResources = []func() resource.Resource{
	NewIntegrationAwsResource,
	NewIntegrationAwsServerlessResource,
	NewIntegrationAzureResource,
	NewIntegrationCrowdstrikeResource,
	NewIntegrationDomainResource,
	NewIntegrationEmailResource,
	NewIntegrationGcpResource,
	NewIntegrationGithubResource,
	NewIntegrationGitlabResource,
	NewIntegrationJiraResource,
	NewIntegrationMsDefenderResource,
	NewIntegrationMs365Resource,
	NewIntegrationOciTenantResource,
	NewIntegrationSentinelOneResource,
	NewIntegrationShodanResource,
	NewIntegrationSlackResource,
	NewIntegrationZendeskResource,
	// Auto-generated resources
	NewIntegrationAzureDevopsResource,
	NewIntegrationGoogleWorkspaceResource,
	NewIntegrationOktaResource,
}
